version: "3.9"

services:
# RabbitMq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

# OrderService
  orderservice:
    build: ./OrderService
    container_name: orderservice
    ports:
      - "8000:8000"
    volumes: 
      - ./OrderService:/app
    depends_on:
      - rabbitmq

# MerchantService
  merchantservice:
    build: ./MerchantService
    container_name: merchantservice
    ports:
      - "8001:8001"
    volumes:
      - ./MerchantService:/app
    depends_on:
      - rabbitmq

# BuyerService
  buyerservice:
    build: ./BuyerService
    container_name: buyerservice
    ports:
      - "8002:8002"
    volumes:
      - ./BuyerService:/app
    depends_on:
      - rabbitmq